### ISSUE TITLE
problem running SquenceMatrix on windows11 64x

### ISSUE THREAD

**Issue by avalerioc** [gaurav/taxondna#101]
I been trying to run SquenceMatrix on my pc and I am having a problem with it... I did upgrade the java version of my pc to the must recent version of java and I am getting the following message:

~>java -jar C:\filo\SequenceMatrix-1.9\SequenceMatrix.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ggvaidya/TaxonDNA/SequenceMatrix/SequenceMatrix has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

can you help me with this problem?

**Comment by avalerioc** [comment]
never mind, I did switch to java jdk-18 and it did the charm! but i does not run at all in java RE

**Comment by gaurav** [comment]
Thanks for letting me know -- please let me know if the problem reoccurs!
