### ISSUE TITLE
Error while trying to open despite following advice

### ISSUE THREAD

**Issue by NicolasLouw** [gaurav/taxondna#97]
Good day,
I hope this message finds you well. I am trying to create a matrix for all my separate gene alignments from a multiple sequence alignment run. After successfully downloading sequence matrix, I try to open it using the "open with" (I tried all the options) option. I then receive a warning message and click on open anyway. Unfortunately, when I click open then, I receive an error stating  "Sequence Matrix” is damaged and can’t be opened. You should move it to the Bin". I also changed my system preferences so that it can open any application, but even after doing that, I am still not able to open the program. I have already spent a decent amount of time troubleshooting this issue, so if you have any insight regarding how I can open this program, I would dearly appreciate that. 

Best,
Nicolas

**Comment by gaurav** [comment]
Hi Nicolas!

Huh, that's an odd error. Did you download the latest version as a Zip file from https://github.com/gaurav/taxondna/releases/tag/v1.9? Do you have Java installed on your computer (you can download it from https://www.java.com/en/download/)? If so, try opening Terminal or Command and running:
```
$ java -jar SequenceMatrix.jar
```

(You might need to use the full path to SequenceMatrix.jar -- you can drag the file into your command prompt to get that. For instance, on my laptop, I had to run `java -jar /Users/gaurav/Downloads/SequenceMatrix-1.9/SequenceMatrix.jar`)

Let me know what output that command gives you!

**Comment by HendersonT** [comment]
I am not sure if this is the same issue, but when I tried running the 1.9 version it said it was compiled on a more recent version (55) than my java environment (51) even though I just uninstalled and reinstalled Java. I backdated to version 1.8 and it runs fine. Here is a copy of my error:

`C:\Users\tyler\Downloads\SequenceMatrix-1.9(1)\SequenceMatrix-1.9> java -jar SequenceMatrix.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ggvaidya/TaxonDNA/SequenceMatrix/SequenceMatrix has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

C:\Users\tyler\Downloads\SequenceMatrix-1.9(1)\SequenceMatrix-1.9>`

**Comment by NicolasLouw** [comment]
Hi Gaurav,

Many thanks for getting back to me about this. It worked when I opened it through the terminal just as you suggested. Thank you so much again!

Best,
Nicolas

**Comment by gaurav** [comment]
Yay, glad to hear that! Does it really not work at all if you double-click it? I might need to update the README.

**Comment by gaurav** [comment]
@HendersonT Please test the latest released version and let me know if the problem is still ongoing!
